import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {performance} from 'node:perf_hooks';
import * as THREE from './dist/vendor/three.module.js';
import {t,ctx,els} from './tools/controller-harness.mjs';
import {AIRPORT,VILLA,HOME,CHARACTERS,areaPoint,insideArea} from './dist/gameplay-areas.js';
import {VEHICLES} from './dist/vehicles.js';
import {NPC_VEHICLES} from './dist/modern-vehicles.js';
import {SPECIAL_VEHICLES} from './dist/special-vehicles.js';
assert(Object.keys(SPECIAL_VEHICLES).every(id=>!NPC_VEHICLES[id]),'new IDs must not replace existing traffic models');
import {Cannon,COMBAT_LIMITS,predictiveAim,staticHit} from './dist/combat.js';
import {vehicleBlocked} from './dist/movement.js';
import {dist,SpatialIndex} from './dist/core.js';
const api=vm.runInContext('({gameplay,poseVehicle,raiseWanted,explodePlayer,respawnAtVilla,ejectParachute,selectCharacter,incidents,updateTraffic,updatePeople,updatePolice,animate})',ctx);
const report={browser:{rendered:false,reason:'Cloud Chrome reports GL_RENDERER=Disabled; GPU/device FPS and visual flight QA remain pending.'}};
const gp=api.gameplay;
const hide=()=>{t.clearPolice();t.cancelMission(false);t.waterRecovery.reset();api.incidents.recovery=null;t.keys.clear();for(const c of t.cars)c.mesh.visible=false;for(const p of t.people)p.mesh.visible=false;gp.cannon.clear();gp.graceUntil=0;Object.assign(t.state,{parachuting:false,respawnHome:false,health:100,speed:0,knockX:0,knockZ:0,spin:0});};
function board(c){c.mesh.visible=true;c.health=100;c.speed=0;Object.assign(t.state,{mode:'foot',car:null,x:c.x+Math.cos(c.yaw)*(c.spec.width/2+1),z:c.z-Math.sin(c.yaw)*(c.spec.width/2+1),y:c.y,speed:0,health:100});t.toggleVehicle();assert(t.state.car===c,'E boards '+c.style+' / mode='+t.state.mode+' / '+els.get('toast').textContent);}
function step(n,keys=[],systems=false){t.keys.clear();keys.forEach(k=>t.keys.add(k));for(let i=0;i<n;i++){if(systems)t.simulate(1/60);else{t.state.elapsed+=1/60;t.movePlayer(1/60);}}t.keys.clear();}
function placeCar(c,p,yaw=AIRPORT.yaw){Object.assign(c,{x:p.x,z:p.z,yaw,y:t.terrain.height(p.x,p.z),speed:0,health:100});api.poseVehicle(c);}
hide();
// Flat, dry and unobstructed across the entire full-size runway, not just endpoints.
let maxDelta=0,samples=0;for(const u of [-10,0,10]){let last;for(let v=-558;v<=558;v+=2){const p=areaPoint(AIRPORT,u,v),y=t.terrain.height(p.x,p.z);assert(t.terrain.dry(p.x,p.z,2,y),'wet runway '+JSON.stringify({u,v,p}));assert(!vehicleBlocked(p.x,p.z,AIRPORT.yaw,t.world.collision,VEHICLES.libellula,y),'blocked runway '+JSON.stringify({u,v,p}));if(last!==undefined)maxDelta=Math.max(maxDelta,Math.abs(y-last));last=y;samples++;}}assert(maxDelta<.04,'runway vertical discontinuity '+maxDelta);
for(const r of t.world.data.gameplay.roads){for(let i=1;i<r.p.length;i++){const a=r.p[i-1],b=r.p[i],len=Math.hypot(b[0]-a[0],b[1]-a[1]),yaw=Math.atan2(b[0]-a[0],b[1]-a[1]);for(let d=0;d<=len;d+=1){const x=a[0]+(b[0]-a[0])*d/len,z=a[1]+(b[1]-a[1])*d/len,y=t.terrain.height(x,z);assert(t.terrain.dry(x,z,1,y),'wet access '+r.n);assert(!vehicleBlocked(x,z,yaw,t.world.collision,VEHICLES.mito,y),'blocked access '+r.n+' '+JSON.stringify({x,z}));}}}
// Open portals are collision-tested with both car and aircraft extents.
for(const v of [42,110,-228,-295])for(let u=125;u<=187;u+=1){const p=areaPoint(AIRPORT,u,v),spec=v>0?VEHICLES.libellula:VEHICLES.tank;assert(!vehicleBlocked(p.x,p.z,AIRPORT.yaw+Math.PI/2,t.world.collision,spec,t.terrain.height(p.x,p.z)),'hangar portal '+v+' / '+u);}
report.airport={runwaySamples:samples,maxHeightDeltaPer2m:maxDelta,connectedAccessRoads:t.world.data.gameplay.roads.length,enterableHangars:4};console.log('PASS airport runway, access roads and enterable hangars');
const tank=t.cars.find(c=>c.style==='tank');assert(tank);for(const c of t.cars.filter(c=>c.fixedSpawn)){hide();board(c);t.state.speed=0;t.toggleVehicle();assert.equal(t.state.mode,'foot','E exits '+c.style);}
console.log('PASS E entry/exit for all airport vehicles');
hide();placeCar(tank,areaPoint(AIRPORT,0,-350));board(tank);const start={x:t.state.x,z:t.state.z};step(240,['KeyW']);assert(dist(start,t.state)>25);assert(t.state.speed>10&&t.state.speed<17);t.state.speed=0;const yaw=t.state.yaw;step(120,['KeyA']);assert(Math.abs(t.state.yaw-yaw)>.8,'tank pivots when stopped');
console.log('PASS tank acceleration and pivot');
// Collision armor on an actual authored hangar wall.
placeCar(tank,areaPoint(AIRPORT,185,-228),AIRPORT.yaw+Math.PI/2);board(tank);step(180,['KeyW']);assert(t.state.health>80,'tank resists a low-speed wall collision');assert(!vehicleBlocked(t.state.x,t.state.z,t.state.yaw,t.world.collision,tank.spec,t.state.y));
console.log('PASS tank wall armor');
report.tank={entryExit:true,movement:true,pivot:true,armor:true};
// Player TAB input, rate limiting and actual car/NPC impacts on the clear runway.
hide();placeCar(tank,areaPoint(AIRPORT,0,-300));board(tank);const victim=t.addCar(tank.x+Math.sin(tank.yaw)*32,tank.z+Math.cos(tank.yaw)*32,tank.yaw,false,true,'sedan');const fired=gp.cannon.stats.fired;tank.fireAt=0;step(1,['Tab']);assert.equal(gp.cannon.stats.fired,fired+1);step(60,['Tab']);assert.equal(gp.cannon.stats.fired,fired+1,'TAB cooldown');for(let i=0;i<60;i++){t.state.elapsed+=1/60;gp.cannon.update(1/60,t.state.elapsed,[t.state,victim]);}assert.equal(victim.health,0);assert.equal(victim.mesh.visible,false);
const person=t.people[0];Object.assign(person,{x:tank.x+Math.sin(tank.yaw)*28,z:tank.z+Math.cos(tank.yaw)*28,y:tank.y,health:100,koUntil:0});person.mesh.visible=true;tank.fireAt=0;step(1,['Tab']);for(let i=0;i<60;i++){t.state.elapsed+=1/60;gp.cannon.update(1/60,t.state.elapsed,[t.state,person]);}assert.equal(person.health,0);api.updatePeople(1/60);assert.equal(person.mesh.visible,false,'KO must not immediately respawn');
// Sweep through a thin wall and predictive moving target in a controlled fixture.
const collision=new SpatialIndex(30),wall={p:[[-10,20],[10,20],[10,20.2],[-10,20.2]],minX:-10,maxX:10,minZ:20,maxZ:20.2,minY:0,h:12};collision.add(wall,-10,20,10,20.2);const wallHash=JSON.stringify(wall);let hits=0;const fixture=new Cannon(new THREE.Scene(),{height:()=>0},collision,()=>hits++),owner={x:0,y:0,z:0,yaw:0},behind={x:0,y:0,z:30,yaw:0,health:100,spec:VEHICLES.sedan};fixture.fire(owner,null,0);fixture.update(.3,.3,[behind]);assert.equal(hits,0);assert.equal(fixture.stats.coverHits,1);assert.equal(JSON.stringify(wall),wallHash,'no permanent building changes');
const empty=new SpatialIndex(),moving={x:0,y:0,z:100,yaw:0,health:100,spec:VEHICLES.sedan},velocity={x:24,y:0,z:0};const accurate=new Cannon(new THREE.Scene(),{height:()=>0},empty,()=>hits++);const aim=predictiveAim({x:0,y:2.2,z:0},{x:moving.x,y:1,z:moving.z},velocity);assert(aim.x>0.1);owner.fireAt=0;accurate.fire(owner,aim,0,true);for(let i=0;i<120;i++){moving.x+=velocity.x/60;accurate.update(1/60,(i+1)/60,[moving]);}assert.equal(hits,1,'prediction must hit a moving target with a real projectile');
const fastTarget={x:0,y:0,z:150,yaw:Math.PI/2,health:100,spec:VEHICLES.sedan},fastVelocity={x:85,y:0,z:0},fastCannon=new Cannon(new THREE.Scene(),{height:()=>0},empty,()=>hits++);owner.fireAt=0;fastCannon.fire(owner,predictiveAim({x:0,y:2.2,z:0},{x:0,y:1,z:150},fastVelocity),0,true);for(let i=0;i<180;i++){fastTarget.x+=85/60;fastCannon.update(1/60,(i+1)/60,[fastTarget]);}assert.equal(hits,2,'accurate aim at 306 km/h accounts for the muzzle offset');assert.equal(accurate.shots.length,12);assert.equal(accurate.effects.length,8);
report.cannon={tab:true,cooldown:1.25,carDestroyed:true,npcKO:true,cover:true,buildingUnchanged:true,predictiveHit:true,predictiveHitAt306Kmh:true,limits:COMBAT_LIMITS};console.log('PASS tank handling, cannon cooldown, swept impacts and cover');
// Plane takeoff/landing and parachute use the real player controller.
hide();const plane=t.cars.find(c=>c.spec.plane);placeCar(plane,areaPoint(AIRPORT,0,-470));board(plane);const ground=t.state.y;step(480,['KeyW','Space']);assert(t.state.y>ground+20,'plane must really climb');assert(!api.incidents.recovery);step(60,['ShiftLeft']);assert(t.state.vy<0,'plane descends');api.ejectParachute();assert(t.state.parachuting&&t.state.mode==='foot');const character=t.state.character;for(let i=0;i<1600&&t.state.parachuting;i++)step(1);assert(!t.state.parachuting);assert.equal(t.state.character,character);
hide();placeCar(plane,areaPoint(AIRPORT,0,-450));board(plane);step(280,['KeyW','Space']);assert(t.state.y>ground+8);step(60,['ShiftLeft']);for(let i=0;i<420&&t.state.y>t.terrain.height(t.state.x,t.state.z)+.02;i++)step(1,['ShiftLeft']);assert(!api.incidents.recovery,'controlled landing');step(300,['KeyS']);assert(t.state.speed<.1);t.toggleVehicle();assert.equal(t.state.mode,'foot');
const heli=t.cars.find(c=>c.style==='airone'&&insideArea(AIRPORT,c.home.x,c.home.z));hide();placeCar(heli,heli.home,heli.home.yaw);board(heli);const rotor=heli.mesh.userData.rotor.rotation.y;step(150,['Space'],true);assert(t.state.y>heli.home.y+10);step(300,['ShiftLeft'],true);assert(Math.abs(t.state.y-t.terrain.height(t.state.x,t.state.z))<.1);t.toggleVehicle();assert.equal(t.state.mode,'foot');const asleep=heli.mesh.userData.rotor.rotation.y;step(60,[],true);assert.equal(heli.mesh.userData.rotor.rotation.y,asleep,'parked rotor sleeps');assert.notEqual(asleep,rotor);
hide();const roof=areaPoint(AIRPORT,180,431);placeCar(plane,roof);plane.y=t.terrain.height(roof.x,roof.z)+28;api.poseVehicle(plane);board(plane);api.ejectParachute();for(let i=0;i<800&&t.state.parachuting;i++)step(1,['KeyS']);const roofY=t.state.y;assert(roofY>t.terrain.elevation(t.state.x,t.state.z)+5,'parachute lands on the terminal roof');step(60);assert(Math.abs(t.state.y-roofY)<.01,'walking player remains supported on roof');
report.flight={takeoff:true,landing:true,parachute:true,roofLanding:true,helicopter:true,parkedRotorSleeps:true};console.log('PASS plane, parachute and helicopter controller');
// The wanted level is reached through repeated real cannon input, not a HUD-only value.
hide();t.travel({x:-900,z:-500,name:'Pursuit test'});gp.graceUntil=0;const road=t.dryRoad(t.state,VEHICLES.tank);assert(road);placeCar(tank,road,road.yaw);board(tank);tank.fireAt=0;step(330,['Tab']);assert.equal(t.state.wanted,5);t.updateUI();assert.equal(els.get('wanted').textContent,'★★★★★');gp.nextMilitary=0;gp.update(1/60);assert.equal(gp.military.length,2,'two military units at five stars');const positions=gp.military.map(c=>({c,x:c.x,z:c.z}));for(let i=0;i<360;i++){t.state.elapsed+=1/60;gp.update(1/60);if(api.incidents.recovery)break;}assert(positions.some(p=>dist(p,p.c)>5),'military must pursue');
api.selectCharacter('nico');assert.equal(t.state.character,'nico');
const attacker=gp.military[0];assert(attacker);const exposed=areaPoint(AIRPORT,0,-180),targetRide=t.addCar(exposed.x,exposed.z,AIRPORT.yaw,false,true,'sedan');board(targetRide);placeCar(attacker,areaPoint(AIRPORT,0,-280));attacker.path=[];attacker.pathIndex=0;attacker.routeAt=t.state.elapsed+30;attacker.fireAt=0;gp.cannon.clear();const enemyShots=gp.cannon.stats.fired;
for(let i=0;i<240&&!api.incidents.recovery;i++){t.state.elapsed+=1/60;gp.update(1/60);}assert(gp.cannon.stats.fired>enemyShots,'military actually fires');assert(api.incidents.recovery,'enemy projectile destroys exposed player car');step(120);assert.equal(t.state.mode,'foot');assert(dist(t.state,HOME)<8);assert.equal(t.state.health,100);assert.equal(t.state.wanted,0);assert.equal(gp.military.length,0);assert.equal(t.state.character,'nico');assert.equal(gp.cannon.shots.filter(s=>s.active).length,0);assert.equal(vm.runInContext('cops.length',ctx),0);api.raiseWanted(5);assert.equal(t.state.wanted,0,'respawn grace');assert.equal(CHARACTERS.length,5);assert.deepEqual(CHARACTERS.map(c=>c.name),['Scando','Mattia','Marchese','Milo','Nico']);
report.wanted={fiveStarsThroughTab:true,militaryCount:2,militaryPursuit:true,actualEnemyProjectileDefeat:true,respawnAtTreves:true,healthReset:true,characterRetained:true,enemiesAndShellsCleared:true,graceSeconds:12};console.log('PASS five-star military pursuit and villa respawn');
// Mission route, speed, interception and single exact reward, with crimes enabled.
hide();t.travel({x:-900,z:-500,name:'Mission test'});const car=t.cars.find(c=>c.style==='mito');const p=t.dryRoad(t.state,car.spec);placeCar(car,p,p.yaw);board(car);t.beginMission('portavalori');assert.equal(t.state.mission?.type,'portavalori');const m=t.state.mission,van=m.van;assert(van.speed>=18);const pathLength=van.path.reduce((sum,p,i)=>sum+(i?dist(p,van.path[i-1]):0),0);assert(pathLength>850);let maxSpeed=van.speed;const from={x:van.x,z:van.z};for(let i=0;i<900;i++){t.state.elapsed+=1/60;t.updateMission(1/60);maxSpeed=Math.max(maxSpeed,van.speed);assert(!vehicleBlocked(van.x,van.z,van.yaw,t.world.collision,van.spec,van.y));}assert(maxSpeed>26,'armored van high speed '+maxSpeed);assert(dist(from,van)>120,'armored van progresses');api.raiseWanted(2);assert.equal(t.state.wanted,2);assert(t.state.mission===m,'crimes do not cancel mission');
// A destroyed van still requires a nearby stopped player and a hold; money cannot double-pay.
van.health=0;van.speed=0;van.mesh.visible=false;Object.assign(t.state,{x:van.x+4,z:van.z,y:van.y,speed:0});const money=t.state.money;for(let i=0;i<155;i++){t.state.elapsed+=1/60;t.updateMission(1/60);}assert(t.state.mission===null,'mission completes after capture');assert.equal(t.state.money-money,1000);t.updateMission(1/60);assert.equal(t.state.money-money,1000);assert(!t.cars.includes(van));
report.portavalori={startsMoving:true,routeMetres:pathLength,maxKmh:maxSpeed*3.6,progressMetres:dist(from,van),crimeEnabled:true,reward:1000,paidOnce:true};
const source=fs.readFileSync('dist/game.js','utf8'),menu=source.slice(source.indexOf('function vehiclesMenu'),source.indexOf('function goodNearbyNode'));assert(!menu.includes("'tank'")&&!menu.includes("'libellula'")&&!menu.includes("'portavalori'"));
// Run the actual old/new interpolation loops against the same mapped actors.
// This is a CPU sub-system measurement, deliberately not an FPS/GPU claim.
const baseline=execFileSync('git',['show','405ae9c6659e03e391cbb680ce4e288427b39336:dist/game.js'],{encoding:'utf8'});
function interpolationLoop(text){const at=text.indexOf('function animate'),start=text.indexOf('for(const a of [...cars,...people,...cops])',at),end=text.indexOf('// Chunk creation',start);return vm.runInContext('(function(){const pose=state;'+text.slice(start,end)+'})',ctx);}
vm.runInContext('renderAlpha=.5;for(const a of [...cars,...people,...cops])previousActors.set(a.mesh,{x:a.x,z:a.z,y:a.y,yaw:a.yaw});',ctx);
const oldLoop=interpolationLoop(baseline),newLoop=interpolationLoop(source),originalHeight=t.terrain.height;let queries=0;t.terrain.height=function(...args){queries++;return originalHeight.apply(this,args);};
const measure=fn=>{queries=0;const start=performance.now();for(let i=0;i<120;i++)fn();return {milliseconds:performance.now()-start,terrainQueries:queries};};
const oldCost=measure(oldLoop),newCost=measure(newLoop);t.terrain.height=originalHeight;assert(oldCost.terrainQueries>1000);assert.equal(newCost.terrainQueries,0);
const meshes=c=>{let n=0;c.mesh.traverse(o=>{if(o.isMesh)n++;});return n;};const helicopterMeshes=t.cars.filter(c=>c.style==='airone').map(meshes);assert(helicopterMeshes.every(n=>n<=3),'helicopter mesh budget');
report.performance={interpolation120Frames:{before:oldCost,after:newCost},parkedAI:false,parkedRotorUpdates:0,maxMilitary:2,helicopterMeshes,airportStructureBoxes:t.world.structures.filter(s=>s.kind==='gameplay').length};
for(const c of t.cars)if(c.fixedSpawn)c.mesh.traverse(o=>{if(o.isMesh)assert(o.geometry.attributes.position.array.every(Number.isFinite));});
fs.writeFileSync('docs/airport-test-results.json',JSON.stringify(report,null,2)+'\n');console.log('PASS armored van mission, €1,000 payout, resource limits and menu exclusions');console.log(JSON.stringify(report,null,2));
