import * as dealerPreviewModule from '../dist/dealer-configurator-preview.js';
import * as coachworkModule from '../dist/car-coachwork.js';
import * as vehicleContactModule from '../dist/vehicle-contact.js';
import * as bikerClubModule from '../dist/biker-club.js';
import * as bikerProgressModule from '../dist/biker-club-progress.js';
import * as npcSpawnModule from '../dist/npc-spawn-policy.js';
import * as stuntTrafficModule from '../dist/stunt-traffic.js';
import * as flightExitModule from '../dist/flight-exit.js';
import * as perfOverlay from '../dist/performance-overlay.js';
import * as inputModule from '../dist/InputManager.js';
import * as taxiDispatcherModule from '../dist/TaxiDispatcher.js';
import * as taxiLoadingOverlayModule from '../dist/TaxiLoadingOverlay.js';
import * as taxiDriverModule from '../dist/TaxiDriverNPC.js';
import * as taxiPathfinderModule from '../dist/Pathfinder.js';
import * as taxiSystemModule from '../dist/TaxiSystem.js';
import * as taxiMenuControllerModule from '../dist/TaxiMenuController.js';
import * as raceDrivingRules from '../dist/race-driving-rules.js';
import * as groundDynamics from '../dist/vehicle-dynamics.js';
import * as footController from '../dist/foot-controller.js';
import * as characterModule from '../dist/characters.js';
import * as qualityModule from '../dist/quality.js';
import * as fullscreenModule from '../dist/fullscreen.js';
import * as gameplayAreas from '../dist/gameplay-areas.js';
import * as specialVehicles from '../dist/special-vehicles.js';
import * as modernGameplay from '../dist/modern-gameplay.js';
import * as modernVehicles from '../dist/modern-vehicles.js';
import * as modernDriving from '../dist/modern-driving.js';
import * as cameraModule from '../dist/camera-rig.js';
import * as districtModule from '../dist/districts.js';
import * as trafficModule from '../dist/traffic.js';
import * as tramModule from '../dist/tram.js';
import * as incidentModule from '../dist/incidents.js';
import * as regionalWorldModule from '../dist/regional-world.js';
import * as regionalAirModule from '../dist/regional-air-traffic.js';
import * as unifiedMapModule from '../dist/unified-map.js';
import * as mapTilesModule from '../dist/map-live-tiles.js';
import * as localRespawnModule from '../dist/local-respawn.js';
import * as waterGameplayModule from '../dist/water-gameplay.js';
import * as nauticalModule from '../dist/nautical-catalog.js';
import * as michelangeloModule from '../dist/unified-michelangelo.js';
import * as pickupModule from '../dist/unified-vehicle-pickup.js';
import * as padovaBoatsModule from '../dist/padova-boats.js';
import * as regionsModule from '../dist/unified-regions.js';
import * as loadingModule from '../dist/loading-resilience.js';
import * as dealershipsModule from '../dist/dealerships.js';
import {SpeedCameras} from '../dist/speed-cameras.js';
import fs from 'node:fs';
import {updateHUDState} from '../dist/compact-hud.js';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import * as THREE from '../dist/vendor/three.module.js';
import * as core from '../dist/core.js';
import * as worldModule from '../dist/world.js';
import * as movement from '../dist/movement.js';
import * as terrainModule from '../dist/terrain.js';
import * as vehicles from '../dist/vehicles.js';
import * as taxiModule from '../dist/taxi-service.js';
import * as portelloModule from '../dist/portello.js';
import * as urbanLifeModule from '../dist/urban-life.js';
import * as vehicleDamageModule from '../dist/vehicle-damage.js';
import {BuildingModels,validateEntry} from '../dist/building-models.js';
import {inspectGLB} from '../dist/model-format.js';
import {GLTFLoader} from '../dist/vendor/GLTFLoader.js';

const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
const els=new Map();const context2d=new Proxy({}, {get:(obj,key)=>obj[key]||(()=>{}),set:(obj,key,val)=>(obj[key]=val,true)});
const element=()=>({style:{},dataset:{},hidden:false,open:false,textContent:'',width:440,height:340,getContext:()=>context2d,addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll:()=>[],querySelector:()=>element(),appendChild(){},append(){},replaceChildren(){},getBoundingClientRect:()=>({width:440,height:340})});
ids.forEach(id=>els.set(id,element()));
const document={head:{appendChild(){}},body:{appendChild(){},style:{setProperty(){}},classList:{add(){},remove(){},contains(){return false;}}},getElementById(id){return els.get(id)||null;},querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},createElement:element};
globalThis.document=document;
const ctx=vm.createContext({...dealerPreviewModule,...coachworkModule,...vehicleContactModule,...bikerClubModule,...bikerProgressModule,...npcSpawnModule,...stuntTrafficModule,...flightExitModule,THREE,SpeedCameras,updateHUDState,...perfOverlay,...inputModule,...taxiDispatcherModule,...taxiLoadingOverlayModule,...taxiDriverModule,...taxiPathfinderModule,...taxiSystemModule,...taxiMenuControllerModule,...groundDynamics,...raceDrivingRules,...footController,...characterModule,...qualityModule,...fullscreenModule,...gameplayAreas,...specialVehicles,...modernGameplay,...modernVehicles,...modernDriving,...cameraModule,...districtModule,...trafficModule,...tramModule,...incidentModule,...regionalWorldModule,...regionalAirModule,...unifiedMapModule,...mapTilesModule,...localRespawnModule,...waterGameplayModule,...nauticalModule,...michelangeloModule,...pickupModule,...padovaBoatsModule,...regionsModule,...loadingModule,...dealershipsModule,...core,...worldModule,...movement,cameraBoom:movement.cameraBoomContinuous,...terrainModule,...vehicles,...taxiModule,...portelloModule,...urbanLifeModule,...vehicleDamageModule,BuildingModels,document,window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},console,Math,JSON,Set,Map,Number,Array,Float32Array,Uint8Array,devicePixelRatio:1,innerWidth:1440,innerHeight:900,requestAnimationFrame(){},location:{reload(){}}});
let code=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/init\(\);\s*$/,'');vm.runInContext(code,ctx);
ctx.testData=JSON.parse(fs.readFileSync(new URL('../dist/data/padova.json',import.meta.url)));
ctx.cityData=JSON.parse(fs.readFileSync(new URL('../dist/data/city.json',import.meta.url)));
ctx.terrainData=JSON.parse(fs.readFileSync(new URL('../dist/data/terrain.json',import.meta.url)));
vm.runInContext(`data=testData;applyCityData(data,cityData);prepareGameplayMap(data);districts=new Districts(data);terrain=new Terrain(terrainData,data,{modern:true});terrain.districts=districts;scene=new THREE.Scene();world=new CityWorld(scene,data,terrain,state.quality);graph=makeRoadGraph(data.roads,{separateLevels:true});patrolGraph=makeRoadGraph(data.roads.filter(r=>r.w>=4&&r.k!=='pedestrian'&&(r.gameplay||!['no','private'].includes(r.access))),{separateLevels:true});signals=new TrafficSignals(graph,data.signals);trams=new Trams(scene,data,terrain);incidents=new Incidents(scene);player=createPerson();camera=new THREE.PerspectiveCamera();sun=new THREE.DirectionalLight();marker=new THREE.Group();state.ready=true;state.started=true;createPopulation();followYaw=state.yaw;cameraRig.reset(state.yaw);`,ctx);
// Taxi was modularized after this harness was written. Do not require removed
// legacy globals just to inspect unrelated systems such as Portello. Existing
// callers receive undefined for obsolete optional functions instead of a VM crash.
const t=vm.runInContext('({setupGameplay,activities,vehiclesMenu,deliverVehicle,get bikerClub(){return bikerClub},placePerson,placeTraffic,placeParkedCar,createBikerGroup,updatePeople,exitAircraft,ejectParachute,terrain,waterRecovery,waterGame,recover,dryRoad,addCar,poseVehicle,travel,falling,state,keys,cars,people,world,scene,player,camera,clock,movePlayer,updateTraffic,updateCamera,updateUI,toggleVehicle,beginMission,cancelMission,updateMission,clearPolice,simulate,graph,callTaxi:typeof callTaxi==="function"?callTaxi:undefined,updateTaxi,beginTaxiTrip:typeof beginTaxiTrip==="function"?beginTaxiTrip:undefined,taxiCanTalk:typeof taxiCanTalk==="function"?taxiCanTalk:undefined})',ctx);
export {t,ctx,els};
