import * as perfOverlay from '../dist/performance-overlay.js';
import * as footController from '../dist/foot-controller.js';
import * as characterModule from '../dist/characters.js';
import * as qualityModule from '../dist/quality.js';
import * as fullscreenModule from '../dist/fullscreen.js';
import * as gameplayAreas from '../dist/gameplay-areas.js';
import * as specialVehicles from '../dist/special-vehicles.js';
import * as modernGameplay from '../dist/modern-gameplay.js';
import * as modernVehicles from '../dist/modern-vehicles.js';
import * as modernDriving from '../dist/modern-driving.js';
import * as cameraModule from '../dist/camera-rig.js';
import * as districtModule from '../dist/districts.js';
import * as trafficModule from '../dist/traffic.js';
import * as tramModule from '../dist/tram.js';
import * as incidentModule from '../dist/incidents.js';
import {SpeedCameras} from '../dist/speed-cameras.js';
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import * as THREE from '../dist/vendor/three.module.js';
import * as core from '../dist/core.js';
import * as worldModule from '../dist/world.js';
import * as movement from '../dist/movement.js';
import * as terrainModule from '../dist/terrain.js';
import * as vehicles from '../dist/vehicles.js';
import {BuildingModels,validateEntry} from '../dist/building-models.js';
import {inspectGLB} from '../dist/model-format.js';
import {GLTFLoader} from '../dist/vendor/GLTFLoader.js';

const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
const els=new Map();const context2d=new Proxy({}, {get:(obj,key)=>obj[key]||(()=>{}),set:(obj,key,val)=>(obj[key]=val,true)});
const element=()=>({style:{},dataset:{},hidden:false,open:false,textContent:'',width:440,height:340,getContext:()=>context2d,addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},querySelectorAll:()=>[],appendChild(){}});
ids.forEach(id=>els.set(id,element()));
const document={body:{classList:{add(){},remove(){}}},getElementById(id){assert(els.has(id),'missing DOM id '+id);return els.get(id);},querySelectorAll:()=>[],addEventListener(){},createElement:element};
globalThis.document=document;
const ctx=vm.createContext({THREE,SpeedCameras,...perfOverlay,...footController,...characterModule,...qualityModule,...fullscreenModule,...gameplayAreas,...specialVehicles,...modernGameplay,...modernVehicles,...modernDriving,...cameraModule,...districtModule,...trafficModule,...tramModule,...incidentModule,...core,...worldModule,...movement,cameraBoom:movement.cameraBoomContinuous,...terrainModule,...vehicles,BuildingModels,document,window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},console,Math,JSON,Set,Map,Number,Array,Float32Array,Uint8Array,devicePixelRatio:1,innerWidth:1440,innerHeight:900,requestAnimationFrame(){},location:{reload(){}}});
let code=fs.readFileSync(new URL('../dist/game.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/init\(\);\s*$/,'');vm.runInContext(code,ctx);
ctx.testData=JSON.parse(fs.readFileSync(new URL('../dist/data/padova.json',import.meta.url)));
ctx.cityData=JSON.parse(fs.readFileSync(new URL('../dist/data/city.json',import.meta.url)));
ctx.terrainData=JSON.parse(fs.readFileSync(new URL('../dist/data/terrain.json',import.meta.url)));
vm.runInContext(`data=testData;applyCityData(data,cityData);prepareGameplayMap(data);districts=new Districts(data);terrain=new Terrain(terrainData,data,{modern:true});terrain.districts=districts;scene=new THREE.Scene();world=new CityWorld(scene,data,terrain,state.quality);graph=makeRoadGraph(data.roads,{separateLevels:true});patrolGraph=makeRoadGraph(data.roads.filter(r=>r.w>=4&&r.k!=='pedestrian'&&(r.gameplay||!['no','private'].includes(r.access))),{separateLevels:true});signals=new TrafficSignals(graph,data.signals);trams=new Trams(scene,data,terrain);incidents=new Incidents(scene);player=createPerson();camera=new THREE.PerspectiveCamera();sun=new THREE.DirectionalLight();marker=new THREE.Group();state.ready=true;state.started=true;createPopulation();followYaw=state.yaw;cameraRig.reset(state.yaw);`,ctx);
const t=vm.runInContext('({terrain,waterRecovery,recover,dryRoad,addCar,travel,falling,state,keys,cars,people,world,scene,player,camera,clock,movePlayer,updateCamera,updateUI,toggleVehicle,beginMission,cancelMission,updateMission,clearPolice,simulate})',ctx);
export {t,ctx,els};
